#!/usr/bin/env node
// posture.mjs — Phase 6 ISMS posture report. Scans records for overdue reviews, due-soon,
// Tier-2 missing required fields, and Tier-2 still-draft (unapproved). Writes a dated Tier-3
// evidence record to evidence/posture/. With --issues-out FILE, emits overdue/incomplete
// Tier-2 items as JSON for the workflow to open as issues.
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, recordFiles, relPosix, parseFrontMatter, addISODuration, daysUntil } from './lib.mjs';

const today = new Date().toISOString().slice(0, 10);
const i = process.argv.indexOf('--issues-out');
const issuesOut = i >= 0 ? process.argv[i + 1] : null;

const overdue = [], dueSoon = [], missing = [], draft = [];
let total = 0;

for (const fp of recordFiles()) {
  const fm = parseFrontMatter(readFileSync(fp, 'utf8'));
  if (!fm) continue;
  total++;
  const rel = relPosix(fp);
  const tier = String(fm['control-tier'] ?? '');
  const t2 = tier === '2' || tier === '3';
  if (fm['last-reviewed'] && fm['review-interval']) {
    const next = addISODuration(fm['last-reviewed'], fm['review-interval']);
    const d = next ? daysUntil(next) : null;
    if (d !== null && d < 0 && t2) overdue.push({ rel, next, days: -d, id: fm.id || '' });
    else if (d !== null && d >= 0 && d <= 30) dueSoon.push({ rel, next, days: d });
  }
  if (t2) {
    const miss = ['owner', 'approved-by', 'approved-on', 'retention'].filter((k) => !fm[k]);
    if (miss.length) missing.push({ rel, miss, id: fm.id || '' });
    if (fm.status === 'draft') draft.push({ rel, id: fm.id || '' });
  }
}

const li = (a) => (a.length ? a.map((x) => `- ${x}`).join('\n') : '_none_');
const head = [
  '---', `id: REC-EVID-POSTURE-${today}`, `title: ISMS posture report ${today}`,
  'class: evidence', 'owner: founder', 'status: approved', 'classification: internal',
  'control-tier: 3', `created: ${today}`, `last-reviewed: ${today}`, 'review-interval: P3M',
  'approved-by: evidence-agent', `approved-on: ${today}`, 'retention: P3Y', '---', '',
].join('\n');
const body = [
  `# ISMS posture report — ${today}`, '',
  `Generated by the Phase 6 evidence agent. Records scanned: **${total}**.`, '',
  `## Overdue reviews (Tier ≥ 2) — ${overdue.length}`,
  li(overdue.map((o) => `\`${o.id || o.rel}\` — was due ${o.next} (${o.days}d overdue)`)), '',
  `## Due soon (≤30d) — ${dueSoon.length}`,
  li(dueSoon.map((o) => `\`${o.rel}\` — ${o.next} (${o.days}d)`)), '',
  `## Tier ≥ 2 missing required fields — ${missing.length}`,
  li(missing.map((m) => `\`${m.id || m.rel}\` — missing ${m.miss.join(', ')}`)), '',
  `## Tier ≥ 2 still draft / unapproved — ${draft.length}`,
  li(draft.map((m) => `\`${m.id || m.rel}\``)), '',
  '> This report is itself a Tier-3 evidence record (append-only intent).', '',
].join('\n');

const dir = join(ROOT, 'evidence', 'posture');
mkdirSync(dir, { recursive: true });
const out = join(dir, `${today}-posture.md`);
writeFileSync(out, head + body);
console.log(`posture: wrote ${out} — overdue ${overdue.length}, due-soon ${dueSoon.length}, missing ${missing.length}, draft ${draft.length}`);

if (issuesOut) {
  const issues = [
    ...overdue.map((o) => ({ title: `Records: review overdue — ${o.id || o.rel}`,
      body: `\`${o.rel}\` review was due ${o.next} (${o.days}d overdue). Review + bump last-reviewed, or supersede.` })),
    ...missing.map((m) => ({ title: `Records: Tier-2 missing fields — ${m.id || m.rel}`,
      body: `\`${m.rel}\` is missing required field(s): ${m.miss.join(', ')}.` })),
  ];
  writeFileSync(issuesOut, JSON.stringify(issues, null, 2));
  console.log(`posture: wrote ${issues.length} issue(s) to ${issuesOut}`);
}
