#!/usr/bin/env node
// register.mjs — generate records/register.yaml from source (Phase 2).
//   node scripts/records/register.mjs            # write the register
//   node scripts/records/register.mjs --check    # warn (or, with RECORDS_ENFORCE=1, fail) on drift
// The register is GENERATED, never hand-edited. Deterministic: same tree → byte-identical file.
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, recordFiles, relPosix, parseFrontMatter, addISODuration, ENFORCE } from './lib.mjs';

const OUT = join(ROOT, 'records', 'register.yaml');
const CHECK = process.argv.includes('--check');

const FIELDS = ['title', 'class', 'status', 'classification', 'control-tier',
  'owner', 'last-reviewed', 'review-interval', 'next-review', 'retention', 'path'];

function collect() {
  const recs = [];
  for (const fp of recordFiles()) {
    const fm = parseFrontMatter(readFileSync(fp, 'utf8'));
    if (!fm) continue; // unstamped files are not yet managed records
    recs.push({
      id: fm.id || `UNSET:${relPosix(fp)}`,
      title: fm.title || '', class: fm.class || '', status: fm.status || '',
      classification: fm.classification || '', 'control-tier': fm['control-tier'] ?? '',
      owner: fm.owner || '', 'last-reviewed': fm['last-reviewed'] || '',
      'review-interval': fm['review-interval'] || '',
      'next-review': addISODuration(fm['last-reviewed'], fm['review-interval']) || '',
      retention: fm.retention || '', path: relPosix(fp),
    });
  }
  const ledger = join(ROOT, 'evidence', 'ledger.jsonl');
  if (existsSync(ledger)) {
    readFileSync(ledger, 'utf8').split(/\r?\n/).filter(Boolean).forEach((ln, i) => {
      try {
        const o = JSON.parse(ln);
        recs.push({
          id: o.id || `LEDGER-${String(i + 1).padStart(4, '0')}`,
          title: o.title || o.event || '', class: 'evidence', status: o.status || '',
          classification: o.classification || 'internal', 'control-tier': 3,
          owner: o.owner || '', 'last-reviewed': o.date || '', 'review-interval': '',
          'next-review': '', retention: o.retention || 'permanent',
          path: `evidence/ledger.jsonl#${i + 1}`,
        });
      } catch { /* skip malformed line; frontmatter/ledger guards report it */ }
    });
  }
  recs.sort((a, b) => String(a.id).localeCompare(String(b.id)) || a.path.localeCompare(b.path));
  return recs;
}

const esc = (v) => {
  const s = String(v);
  return (s === '' || /[:#[\]{}",&*?|<>=!%@`]/.test(s)) ? JSON.stringify(s) : s;
};

function toYaml(recs) {
  let out = '# GENERATED by scripts/records/register.mjs — do not edit by hand.\n';
  out += `# count: ${recs.length}\n`;
  out += 'records:\n';
  for (const r of recs) {
    out += `  - id: ${esc(r.id)}\n`;
    for (const f of FIELDS) out += `    ${f}: ${esc(r[f])}\n`;
  }
  return out;
}

const yaml = toYaml(collect());

if (CHECK) {
  const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (cur !== yaml) {
    console.log('::warning::records/register.yaml is stale — run `node scripts/records/register.mjs` and commit.');
    process.exit(ENFORCE ? 1 : 0);
  }
  console.log('register-verify: up to date.');
} else {
  writeFileSync(OUT, yaml);
  console.log(`wrote ${OUT} (${yaml.split('\n').length} lines)`);
}
