/**
 * Single data layer: workspaces, projects, environments, api_keys (Gateway keys). Uses Neon Postgres only.
 * Requires DATABASE_URL. Schema: migrations 001–003.
 */
export {
  upsertUser,
  getOrCreateDefaultWorkspace,
  getWorkspace,
  listProjects,
  listProjectsByWorkspace,
  getProjectInWorkspace,
  createProject,
  getProject,
  updateProject,
  deleteProject,
  listEnvironments,
  listApiKeys,
  createApiKey,
  deleteApiKey,
  insertAuditEvent,
  listAuditEvents,
  listProviderIntegrations,
  getProviderIntegration,
  createProviderIntegration,
  updateProviderIntegration,
  deleteProviderIntegration,
  updateProviderVerification,
  listProviderBindingsByIntegration,
  listProviderBindingsByProject,
  createProviderBinding,
  deleteProviderBinding,
  type Workspace,
  type Project,
  type Environment,
  type ApiKeyRecord,
  type AuditEventRecord,
  listModels,
  getModel,
  getModelsLifecycleByIds,
  listProviderModelVariants,
  type ModelLifecycleInfo,
  getEnvironmentInProject,
  listRoutes,
  getRoute,
  createRoute,
  updateRoute,
  deleteRoute,
  listRouteSteps,
  createRouteStep,
  updateRouteStep,
  deleteRouteStep,
  getRouteWithSteps,
  listPolicies,
  getPolicy,
  createPolicy,
  updatePolicy,
  deletePolicy,
  listPolicyBindings,
  listPolicyBindingsByTarget,
  createPolicyBinding,
  deletePolicyBinding,
  evaluatePolicies,
  type ModelRecord,
  type ProviderModelVariantRecord,
  type ListModelsFilters,
  type RouteRecord,
  type RouteStepRecord,
  type PolicyRecord,
  type PolicyBindingRecord,
  type PolicyEvaluationContext,
  type PolicyViolation,
  type ProviderIntegrationRecord,
  type ProviderBindingRecord,
  insertRequestLog,
  listRequestLogs,
  listUsageAggregates,
  aggregateRequestLogsToUsage,
  insertUsageAggregate,
  setWorkspacePlan,
  type RequestLogParams,
  type RequestLogRecord,
  type ListRequestLogsFilters,
  type UsageAggregateRecord,
  type ListUsageAggregatesFilters,
  type InsertUsageAggregateParams,
} from "$lib/server/neon";
