/**
 * Single data layer: workspaces, projects, environments, api_keys (Gateway keys). Uses Neon Postgres only.
 * Requires DATABASE_URL. Schema: migrations 001–003.
 */
export {
  upsertUser,
  getOrCreateDefaultWorkspace,
  getWorkspace,
  listProjects,
  listProjectsByWorkspace,
  getProjectInWorkspace,
  getProjectById,
  createProject,
  ensureRestormelTestingProject,
  getProject,
  updateProject,
  deleteProject,
  listEnvironments,
  getProjectDefaultEnvironmentId,
  listApiKeys,
  countApiKeysByWorkspace,
  createApiKey,
  deleteApiKey,
  insertAuditEvent,
  listAuditEvents,
  listProviderIntegrations,
  getProviderIntegration,
  getProviderIntegrationSecretRow,
  createProviderIntegration,
  updateProviderIntegration,
  deleteProviderIntegration,
  updateProviderVerification,
  listProviderBindingsByIntegration,
  listProviderBindingsByProject,
  createProviderBinding,
  deleteProviderBinding,
  type Workspace,
  type Project,
  type Environment,
  type ApiKeyRecord,
  type AuditEventRecord,
  listModels,
  getModel,
  getModelsLifecycleByIds,
  listProviderModelVariants,
  listProviderModelVariantsByModelIds,
  listProjectModelBindings,
  getProjectModelBinding,
  upsertProjectModelBinding,
  getProjectModelBindingByLogicalRef,
  updateProjectModelBindingEnabled,
  deleteProjectModelBinding,
  replaceProjectModelBindings,
  type ProjectModelBindingRecord,
  type ProjectModelBindingKind,
  upsertCatalogModelObservation,
  listCatalogModelObservationsForPairs,
  type CatalogModelObservationRecord,
  type ModelLifecycleInfo,
  getEnvironmentInProject,
  listRoutes,
  getRoute,
  createRoute,
  updateRoute,
  deleteRoute,
  listRouteSteps,
  listRouteStepsByProject,
  createRouteStep,
  updateRouteStep,
  deleteRouteStep,
  getRouteWithSteps,
  listRouteStepEdges,
  replaceRouteStepEdges,
  insertRouteVersionEvent,
  listRouteVersionEvents,
  getRouteVersionEventByVersion,
  replaceRouteStepsFromSnapshot,
  type RouteVersionEventRecord,
  listPolicies,
  getPolicy,
  createPolicy,
  updatePolicy,
  deletePolicy,
  listPolicyBindings,
  listPolicyBindingsForWorkspace,
  listPolicyBindingsByTarget,
  getPolicyBindingConflictMessage,
  createPolicyBinding,
  deletePolicyBinding,
  evaluatePolicies,
  insertPolicyVersionEvent,
  listPolicyVersionEvents,
  getPolicyVersionEventByVersion,
  type ModelRecord,
  type ProviderModelVariantRecord,
  type ListModelsFilters,
  type RouteRecord,
  type RouteStepEdgeRecord,
  type RouteStepRecord,
  type PolicyRecord,
  type PolicyVersionEventRecord,
  type PolicyBindingRecord,
  type PolicyEvaluationContext,
  type PolicyViolation,
  type ProviderIntegrationRecord,
  type ProviderBindingRecord,
  insertRequestLog,
  listRequestLogs,
  listUsageAggregates,
  aggregateRequestLogsToUsage,
  getRequestLogCountsByUtcDay,
  getEstimatedCostUsdByModel,
  insertFoundersApplication,
  countFoundersApplications,
  insertHostedRuntimeJob,
  getHostedRuntimeJobForProject,
  getHostedRuntimeJobById,
  findHostedRuntimeJobByIdempotencyKey,
  hashHostedRuntimeIdempotencyKey,
  claimNextQueuedHostedRuntimeJob,
  setHostedRuntimeJobCancelRequested,
  updateHostedRuntimeJobById,
  type HostedRuntimeJobRecord,
  insertUsageAggregate,
  setWorkspacePlan,
  findWorkspaceByPaddleSubscriptionId,
  findWorkspaceByPaddleCustomerId,
  applyPaddleLifecycleUpdate,
  downgradeWorkspaceIfProExpired,
  getAuthUserSignupRank,
  foundingPromoMaxUsers,
  foundingPromoMonths,
  type RequestLogParams,
  type RequestLogRecord,
  type ListRequestLogsFilters,
  type UsageAggregateRecord,
  type ListUsageAggregatesFilters,
  type InsertUsageAggregateParams,
  listWorkspaceWebhooks,
  createWorkspaceWebhook,
  deleteWorkspaceWebhook,
  type WorkspaceWebhookRecord,
} from "$lib/server/neon";
